const CITIES = [
  "Belo Horizonte",
  "Contagem",
  "Uberlândia",
  "Juiz de Fora",
  "Ribeirão das Neves",
  "Betim",
  "Montes Claros",
  "Uberaba",
  "Governador Valadares",
  "Santa Luzia",
  "Ipatinga",
  "Sete Lagoas",
  "Divinópolis",
  "Poços de Caldas",
  "Ibirité"
];

const CITY_CONNECTIONS = [
  ['Belo Horizonte', 'Contagem', 19],
  ['Belo Horizonte', 'Uberlândia', 536],
  ['Belo Horizonte', 'Juiz de Fora', 261],
  ['Belo Horizonte', 'Ribeirão das Neves', 34],
  ['Belo Horizonte', 'Betim', 30],
  ['Belo Horizonte', 'Montes Claros', 425],
  ['Belo Horizonte', 'Uberaba', 475],
  ['Belo Horizonte', 'Governador Valadares', 317],
  ['Belo Horizonte', 'Santa Luzia', 24],
  ['Belo Horizonte', 'Ipatinga', 218],
  ['Belo Horizonte', 'Sete Lagoas', 75],
  ['Belo Horizonte', 'Divinópolis', 151],
  ['Belo Horizonte', 'Poços de Caldas', 462],
  ['Belo Horizonte', 'Ibirité', 21],
  ['Contagem', 'Belo Horizonte', 19],
  ['Contagem', 'Uberlândia', 523],
  ['Contagem', 'Juiz de Fora', 270],
  ['Contagem', 'Ribeirão das Neves', 27],
  ['Contagem', 'Betim', 17],
  ['Contagem', 'Montes Claros', 418],
  ['Contagem', 'Uberaba', 462],
  ['Contagem', 'Governador Valadares', 334],
  ['Contagem', 'Santa Luzia', 41],
  ['Contagem', 'Ipatinga', 235],
  ['Contagem', 'Sete Lagoas', 66],
  ['Contagem', 'Divinópolis', 139],
  ['Contagem', 'Poços de Caldas', 449],
  ['Contagem', 'Ibirité', 19],
  ['Uberlândia', 'Belo Horizonte', 536],
  ['Uberlândia', 'Contagem', 523],
  ['Uberlândia', 'Juiz de Fora', 785],
  ['Uberlândia', 'Ribeirão das Neves', 547],
  ['Uberlândia', 'Betim', 506],
  ['Uberlândia', 'Montes Claros', 627],
  ['Uberlândia', 'Uberaba', 106],
  ['Uberlândia', 'Governador Valadares', 851],
  ['Uberlândia', 'Santa Luzia', 558],
  ['Uberlândia', 'Ipatinga', 751],
  ['Uberlândia', 'Sete Lagoas', 596],
  ['Uberlândia', 'Divinópolis', 458],
  ['Uberlândia', 'Poços de Caldas', 474],
  ['Uberlândia', 'Ibirité', 524],
  ['Juiz de Fora', 'Belo Horizonte', 261],
  ['Juiz de Fora', 'Contagem', 271],
  ['Juiz de Fora', 'Uberlândia', 787],
  ['Juiz de Fora', 'Ribeirão das Neves', 286],
  ['Juiz de Fora', 'Betim', 280],
  ['Juiz de Fora', 'Montes Claros', 678],
  ['Juiz de Fora', 'Uberaba', 726],
  ['Juiz de Fora', 'Governador Valadares', 454],
  ['Juiz de Fora', 'Santa Luzia', 284],
  ['Juiz de Fora', 'Ipatinga', 426],
  ['Juiz de Fora', 'Sete Lagoas', 325],
  ['Juiz de Fora', 'Divinópolis', 322],
  ['Juiz de Fora', 'Poços de Caldas', 460],
  ['Juiz de Fora', 'Ibirité', 268],
  ['Ribeirão das Neves', 'Belo Horizonte', 33],
  ['Ribeirão das Neves', 'Contagem', 28],
  ['Ribeirão das Neves', 'Uberlândia', 552],
  ['Ribeirão das Neves', 'Juiz de Fora', 291],
  ['Ribeirão das Neves', 'Betim', 46],
  ['Ribeirão das Neves', 'Montes Claros', 398],
  ['Ribeirão das Neves', 'Uberaba', 491],
  ['Ribeirão das Neves', 'Governador Valadares', 334],
  ['Ribeirão das Neves', 'Santa Luzia', 33],
  ['Ribeirão das Neves', 'Ipatinga', 235],
  ['Ribeirão das Neves', 'Sete Lagoas', 46],
  ['Ribeirão das Neves', 'Divinópolis', 168],
  ['Ribeirão das Neves', 'Poços de Caldas', 478],
  ['Ribeirão das Neves', 'Ibirité', 44],
  ['Betim', 'Belo Horizonte', 25],
  ['Betim', 'Contagem', 15],
  ['Betim', 'Uberlândia', 384],
  ['Betim', 'Juiz de Fora', 205],
  ['Betim', 'Ribeirão das Neves', 33],
  ['Betim', 'Montes Claros', 310],
  ['Betim', 'Uberaba', 339],
  ['Betim', 'Governador Valadares', 282],
  ['Betim', 'Santa Luzia', 46],
  ['Betim', 'Ipatinga', 208],
  ['Betim', 'Sete Lagoas', 63],
  ['Betim', 'Divinópolis', 85],
  ['Betim', 'Poços de Caldas', 333],
  ['Betim', 'Ibirité', 22],
  ['Montes Claros', 'Belo Horizonte', 304],
  ['Montes Claros', 'Contagem', 296],
  ['Montes Claros', 'Uberlândia', 447],
  ['Montes Claros', 'Juiz de Fora', 487],
  ['Montes Claros', 'Ribeirão das Neves', 282],
  ['Montes Claros', 'Betim', 308],
  ['Montes Claros', 'Uberaba', 486],
  ['Montes Claros', 'Governador Valadares', 388],
  ['Montes Claros', 'Santa Luzia', 310],
  ['Montes Claros', 'Ipatinga', 377],
  ['Montes Claros', 'Sete Lagoas', 256],
  ['Montes Claros', 'Divinópolis', 390],
  ['Montes Claros', 'Poços de Caldas', 636],
  ['Montes Claros', 'Ibirité', 309],
  ['Uberaba', 'Belo Horizonte', 362],
  ['Uberaba', 'Contagem', 352],
  ['Uberaba', 'Uberlândia', 72],
  ['Uberaba', 'Juiz de Fora', 543],
  ['Uberaba', 'Ribeirão das Neves', 370],
  ['Uberaba', 'Betim', 342],
  ['Uberaba', 'Montes Claros', 486],
  ['Uberaba', 'Governador Valadares', 619],
  ['Uberaba', 'Santa Luzia', 383],
  ['Uberaba', 'Ipatinga', 545],
  ['Uberaba', 'Sete Lagoas', 382],
  ['Uberaba', 'Divinópolis', 312],
  ['Uberaba', 'Poços de Caldas', 259],
  ['Uberaba', 'Ibirité', 357],
  ['Governador Valadares', 'Belo Horizonte', 270],
  ['Governador Valadares', 'Contagem', 280],
  ['Governador Valadares', 'Uberlândia', 672],
  ['Governador Valadares', 'Juiz de Fora', 328],
  ['Governador Valadares', 'Ribeirão das Neves', 284],
  ['Governador Valadares', 'Betim', 292],
  ['Governador Valadares', 'Montes Claros', 386],
  ['Governador Valadares', 'Uberaba', 627],
  ['Governador Valadares', 'Santa Luzia', 260],
  ['Governador Valadares', 'Ipatinga', 77],
  ['Governador Valadares', 'Sete Lagoas', 311],
  ['Governador Valadares', 'Divinópolis', 373],
  ['Governador Valadares', 'Poços de Caldas', 620],
  ['Governador Valadares', 'Ibirité', 286],
  ['Santa Luzia', 'Belo Horizonte', 26],
  ['Santa Luzia', 'Contagem', 37],
  ['Santa Luzia', 'Uberlândia', 429],
  ['Santa Luzia', 'Juiz de Fora', 216],
  ['Santa Luzia', 'Ribeirão das Neves', 30],
  ['Santa Luzia', 'Betim', 48],
  ['Santa Luzia', 'Montes Claros', 308],
  ['Santa Luzia', 'Uberaba', 383],
  ['Santa Luzia', 'Governador Valadares', 253],
  ['Santa Luzia', 'Ipatinga', 187],
  ['Santa Luzia', 'Sete Lagoas', 55],
  ['Santa Luzia', 'Divinópolis', 128],
  ['Santa Luzia', 'Poços de Caldas', 366],
  ['Santa Luzia', 'Ibirité', 43],
  ['Ipatinga', 'Belo Horizonte', 196],
  ['Ipatinga', 'Contagem', 206],
  ['Ipatinga', 'Uberlândia', 598],
  ['Ipatinga', 'Juiz de Fora', 311],
  ['Ipatinga', 'Ribeirão das Neves', 210],
  ['Ipatinga', 'Betim', 218],
  ['Ipatinga', 'Montes Claros', 377],
  ['Ipatinga', 'Uberaba', 553],
  ['Ipatinga', 'Governador Valadares', 78],
  ['Ipatinga', 'Santa Luzia', 187],
  ['Ipatinga', 'Sete Lagoas', 229],
  ['Ipatinga', 'Divinópolis', 289],
  ['Ipatinga', 'Poços de Caldas', 528],
  ['Ipatinga', 'Ibirité', 212],
  ['Sete Lagoas', 'Belo Horizonte', 57],
  ['Sete Lagoas', 'Contagem', 50],
  ['Sete Lagoas', 'Uberlândia', 404],
  ['Sete Lagoas', 'Juiz de Fora', 240],
  ['Sete Lagoas', 'Ribeirão das Neves', 35],
  ['Sete Lagoas', 'Betim', 62],
  ['Sete Lagoas', 'Montes Claros', 255],
  ['Sete Lagoas', 'Uberaba', 382],
  ['Sete Lagoas', 'Governador Valadares', 303],
  ['Sete Lagoas', 'Santa Luzia', 55],
  ['Sete Lagoas', 'Ipatinga', 229],
  ['Sete Lagoas', 'Divinópolis', 143],
  ['Sete Lagoas', 'Poços de Caldas', 389],
  ['Sete Lagoas', 'Ibirité', 63],
  ['Divinópolis', 'Belo Horizonte', 107],
  ['Divinópolis', 'Contagem', 97],
  ['Divinópolis', 'Uberlândia', 356],
  ['Divinópolis', 'Juiz de Fora', 251],
  ['Divinópolis', 'Ribeirão das Neves', 114],
  ['Divinópolis', 'Betim', 86],
  ['Divinópolis', 'Montes Claros', 391],
  ['Divinópolis', 'Uberaba', 311],
  ['Divinópolis', 'Governador Valadares', 364],
  ['Divinópolis', 'Santa Luzia', 128],
  ['Divinópolis', 'Ipatinga', 289],
  ['Divinópolis', 'Sete Lagoas', 145],
  ['Divinópolis', 'Poços de Caldas', 304],
  ['Divinópolis', 'Ibirité', 102],
  ['Poços de Caldas', 'Belo Horizonte', 465],
  ['Poços de Caldas', 'Contagem', 456],
  ['Poços de Caldas', 'Uberlândia', 446],
  ['Poços de Caldas', 'Juiz de Fora', 379],
  ['Poços de Caldas', 'Ribeirão das Neves', 353],
  ['Poços de Caldas', 'Betim', 325],
  ['Poços de Caldas', 'Montes Claros', 630],
  ['Poços de Caldas', 'Uberaba', 258],
  ['Poços de Caldas', 'Governador Valadares', 602],
  ['Poços de Caldas', 'Santa Luzia', 366],
  ['Poços de Caldas', 'Ipatinga', 528],
  ['Poços de Caldas', 'Sete Lagoas', 384],
  ['Poços de Caldas', 'Divinópolis', 300],
  ['Poços de Caldas', 'Ibirité', 340],
  ['Ibirité', 'Belo Horizonte', 21],
  ['Ibirité', 'Contagem', 20],
  ['Ibirité', 'Uberlândia', 401],
  ['Ibirité', 'Juiz de Fora', 199],
  ['Ibirité', 'Ribeirão das Neves', 34],
  ['Ibirité', 'Betim', 23],
  ['Ibirité', 'Montes Claros', 312],
  ['Ibirité', 'Uberaba', 356],
  ['Ibirité', 'Governador Valadares', 278],
  ['Ibirité', 'Santa Luzia', 42],
  ['Ibirité', 'Ipatinga', 203],
  ['Ibirité', 'Sete Lagoas', 65],
  ['Ibirité', 'Divinópolis', 103],
  ['Ibirité', 'Poços de Caldas', 349],
];

export { CITIES, CITY_CONNECTIONS }