const CITIES = [
  "Belo Horizonte",
  "Contagem",
  "Uberlândia",
  "Juiz de Fora",
  "Ribeirão das Neves",
  "Betim",
  "Montes Claros",
  "Uberaba",
  "Governador Valadares",
  "Santa Luzia",
  "Ipatinga",
  "Sete Lagoas",
  "Divinópolis",
  "Poços de Caldas",
  "Ibirité"
];

const CITY_CONNECTIONS = [
  ['Belo Horizonte', 'Contagem', 19],
  ['Belo Horizonte', 'Uberlândia', 536],
  ['Belo Horizonte', 'Juiz de Fora', 261],
  ['Belo Horizonte', 'Ribeirão das Neves', 34],
  ['Belo Horizonte', 'Betim', 30],
  ['Belo Horizonte', 'Montes Claros', 425],
  ['Belo Horizonte', 'Uberaba', 475],
  ['Belo Horizonte', 'Governador Valadares', 317],
  ['Belo Horizonte', 'Santa Luzia', 24],
  ['Belo Horizonte', 'Ipatinga', 218],
  ['Belo Horizonte', 'Sete Lagoas', 75],
  ['Belo Horizonte', 'Divinópolis', 151],
  ['Belo Horizonte', 'Poços de Caldas', 462],
  ['Belo Horizonte', 'Ibirité', 21],
  ['Contagem', 'Belo Horizonte', 19],
  ['Contagem', 'Uberlândia', 523],
  ['Contagem', 'Juiz de Fora', 270],
  ['Contagem', 'Ribeirão das Neves', 27],
  ['Contagem', 'Betim', 17],
  ['Contagem', 'Montes Claros', 418],
  ['Contagem', 'Uberaba', 462],
  ['Contagem', 'Governador Valadares', 334],
  ['Contagem', 'Santa Luzia', 41],
  ['Contagem', 'Ipatinga', 235],
  ['Contagem', 'Sete Lagoas', 66],
  ['Contagem', 'Divinópolis', 139],
  ['Contagem', 'Poços de Caldas', 449],
  ['Contagem', 'Ibirité', 19],
  ['Uberlândia', 'Belo Horizonte', 536],
  ['Uberlândia', 'Contagem', 523],
  ['Uberlândia', 'Juiz de Fora', 785],
  ['Uberlândia', 'Ribeirão das Neves', 547],
  ['Uberlândia', 'Betim', 506],
  ['Uberlândia', 'Montes Claros', 627],
  ['Uberlândia', 'Uberaba', 106],
  ['Uberlândia', 'Governador Valadares', 851],
  ['Uberlândia', 'Santa Luzia', 558],
  ['Uberlândia', 'Ipatinga', 751],
  ['Uberlândia', 'Sete Lagoas', 596],
  ['Uberlândia', 'Divinópolis', 458],
  ['Uberlândia', 'Poços de Caldas', 474],
  ['Uberlândia', 'Ibirité', 524],
  ['Juiz de Fora', 'Belo Horizonte', 261],
  ['Juiz de Fora', 'Contagem', 271],
  ['Juiz de Fora', 'Uberlândia', 787],
  ['Juiz de Fora', 'Ribeirão das Neves', 286],
  ['Juiz de Fora', 'Betim', 280],
  ['Juiz de Fora', 'Montes Claros', 678],
  ['Juiz de Fora', 'Uberaba', 726],
  ['Juiz de Fora', 'Governador Valadares', 454],
  ['Juiz de Fora', 'Santa Luzia', 284],
  ['Juiz de Fora', 'Ipatinga', 426],
  ['Juiz de Fora', 'Sete Lagoas', 325],
  ['Juiz de Fora', 'Divinópolis', 322],
  ['Juiz de Fora', 'Poços de Caldas', 460],
  ['Juiz de Fora', 'Ibirité', 268],
  ['Ribeirão das Neves', 'Belo Horizonte', 33],
  ['Ribeirão das Neves', 'Contagem', 28],
  ['Ribeirão das Neves', 'Uberlândia', 552],
  ['Ribeirão das Neves', 'Juiz de Fora', 291],
  ['Ribeirão das Neves', 'Betim', 46],
  ['Ribeirão das Neves', 'Montes Claros', 398],
  ['Ribeirão das Neves', 'Uberaba', 491],
  ['Ribeirão das Neves', 'Governador Valadares', 334],
  ['Ribeirão das Neves', 'Santa Luzia', 33],
  ['Ribeirão das Neves', 'Ipatinga', 235],
  ['Ribeirão das Neves', 'Sete Lagoas', 46],
  ['Ribeirão das Neves', 'Divinópolis', 168],
  ['Ribeirão das Neves', 'Poços de Caldas', 478],
  ['Ribeirão das Neves', 'Ibirité', 44],
  ['Betim', 'Belo Horizonte', 29],
  ['Betim', 'Contagem', 17],
  ['Betim', 'Uberlândia', 506],
  ['Betim', 'Juiz de Fora', 279],
  ['Betim', 'Ribeirão das Neves', 41],
  ['Betim', 'Montes Claros', 433],
  ['Betim', 'Uberaba', 445],
  ['Betim', 'Governador Valadares', 345],
  ['Betim', 'Santa Luzia', 52],
  ['Betim', 'Ipatinga', 245],
  ['Betim', 'Sete Lagoas', 80],
  ['Betim', 'Divinópolis', 121],
  ['Betim', 'Poços de Caldas', 434],
  ['Betim', 'Ibirité', 22],
  ['Montes Claros', 'Belo Horizonte', 425],
  ['Montes Claros', 'Contagem', 415],
  ['Montes Claros', 'Uberlândia', 627],
  ['Montes Claros', 'Juiz de Fora', 677],
  ['Montes Claros', 'Ribeirão das Neves', 399],
  ['Montes Claros', 'Betim', 432],
  ['Montes Claros', 'Uberaba', 648],
  ['Montes Claros', 'Governador Valadares', 535],
  ['Montes Claros', 'Santa Luzia', 433],
  ['Montes Claros', 'Ipatinga', 523],
  ['Montes Claros', 'Sete Lagoas', 360],
  ['Montes Claros', 'Divinópolis', 554],
  ['Montes Claros', 'Poços de Caldas', 865],
  ['Montes Claros', 'Ibirité', 430],
  ['Uberaba', 'Belo Horizonte', 476],
  ['Uberaba', 'Contagem', 463],
  ['Uberaba', 'Uberlândia', 106],
  ['Uberaba', 'Juiz de Fora', 726],
  ['Uberaba', 'Ribeirão das Neves', 488],
  ['Uberaba', 'Betim', 446],
  ['Uberaba', 'Montes Claros', 648],
  ['Uberaba', 'Governador Valadares', 791],
  ['Uberaba', 'Santa Luzia', 498],
  ['Uberaba', 'Ipatinga', 692],
  ['Uberaba', 'Sete Lagoas', 521],
  ['Uberaba', 'Divinópolis', 398],
  ['Uberaba', 'Poços de Caldas', 368],
  ['Uberaba', 'Ibirité', 465],
  ['Governador Valadares', 'Belo Horizonte', 322],
  ['Governador Valadares', 'Contagem', 336],
  ['Governador Valadares', 'Uberlândia', 857],
  ['Governador Valadares', 'Juiz de Fora', 455],
  ['Governador Valadares', 'Ribeirão das Neves', 339],
  ['Governador Valadares', 'Betim', 351],
  ['Governador Valadares', 'Montes Claros', 534],
  ['Governador Valadares', 'Uberaba', 796],
  ['Governador Valadares', 'Santa Luzia', 313],
  ['Governador Valadares', 'Ipatinga', 102],
  ['Governador Valadares', 'Sete Lagoas', 380],
  ['Governador Valadares', 'Divinópolis', 473],
  ['Governador Valadares', 'Poços de Caldas', 783],
  ['Governador Valadares', 'Ibirité', 340],
  ['Santa Luzia', 'Belo Horizonte', 25],
  ['Santa Luzia', 'Contagem', 39],
  ['Santa Luzia', 'Uberlândia', 561],
  ['Santa Luzia', 'Juiz de Fora', 284],
  ['Santa Luzia', 'Ribeirão das Neves', 33],
  ['Santa Luzia', 'Betim', 54],
  ['Santa Luzia', 'Montes Claros', 429],
  ['Santa Luzia', 'Uberaba', 500],
  ['Santa Luzia', 'Governador Valadares', 310],
  ['Santa Luzia', 'Ipatinga', 210],
  ['Santa Luzia', 'Sete Lagoas', 70],
  ['Santa Luzia', 'Divinópolis', 176],
  ['Santa Luzia', 'Poços de Caldas', 487],
  ['Santa Luzia', 'Ibirité', 43],
  ['Ipatinga', 'Belo Horizonte', 223],
  ['Ipatinga', 'Contagem', 236],
  ['Ipatinga', 'Uberlândia', 758],
  ['Ipatinga', 'Juiz de Fora', 428],
  ['Ipatinga', 'Ribeirão das Neves', 240],
  ['Ipatinga', 'Betim', 251],
  ['Ipatinga', 'Montes Claros', 525],
  ['Ipatinga', 'Uberaba', 697],
  ['Ipatinga', 'Governador Valadares', 103],
  ['Ipatinga', 'Santa Luzia', 214],
  ['Ipatinga', 'Sete Lagoas', 281],
  ['Ipatinga', 'Divinópolis', 373],
  ['Ipatinga', 'Poços de Caldas', 684],
  ['Ipatinga', 'Ibirité', 240],
  ['Sete Lagoas', 'Belo Horizonte', 75],
  ['Sete Lagoas', 'Contagem', 63],
  ['Sete Lagoas', 'Uberlândia', 597],
  ['Sete Lagoas', 'Juiz de Fora', 325],
  ['Sete Lagoas', 'Ribeirão das Neves', 47],
  ['Sete Lagoas', 'Betim', 80],
  ['Sete Lagoas', 'Montes Claros', 360],
  ['Sete Lagoas', 'Uberaba', 520],
  ['Sete Lagoas', 'Governador Valadares', 377],
  ['Sete Lagoas', 'Santa Luzia', 73],
  ['Sete Lagoas', 'Ipatinga', 277],
  ['Sete Lagoas', 'Divinópolis', 202],
  ['Sete Lagoas', 'Poços de Caldas', 513],
  ['Sete Lagoas', 'Ibirité', 78],
  ['Divinópolis', 'Belo Horizonte', 117],
  ['Divinópolis', 'Contagem', 104],
  ['Divinópolis', 'Uberlândia', 458],
  ['Divinópolis', 'Juiz de Fora', 322],
  ['Divinópolis', 'Ribeirão das Neves', 129],
  ['Divinópolis', 'Betim', 87],
  ['Divinópolis', 'Montes Claros', 520],
  ['Divinópolis', 'Uberaba', 397],
  ['Divinópolis', 'Governador Valadares', 433],
  ['Divinópolis', 'Santa Luzia', 140],
  ['Divinópolis', 'Ipatinga', 333],
  ['Divinópolis', 'Sete Lagoas', 168],
  ['Divinópolis', 'Poços de Caldas', 390],
  ['Divinópolis', 'Ibirité',  106],
  ['Poços de Caldas', 'Belo Horizonte', 462],
  ['Poços de Caldas', 'Contagem', 449],
  ['Poços de Caldas', 'Uberlândia', 474],
  ['Poços de Caldas', 'Juiz de Fora', 458],
  ['Poços de Caldas', 'Ribeirão das Neves', 473],
  ['Poços de Caldas', 'Betim', 434],
  ['Poços de Caldas', 'Montes Claros', 865],
  ['Poços de Caldas', 'Uberaba', 366],
  ['Poços de Caldas', 'Governador Valadares', 777],
  ['Poços de Caldas', 'Santa Luzia', 484],
  ['Poços de Caldas', 'Ipatinga', 677],
  ['Poços de Caldas', 'Sete Lagoas', 512],
  ['Poços de Caldas', 'Divinópolis', 390],
  ['Poços de Caldas', 'Ibirité', 450],
  ['Ibirité', 'Belo Horizonte', 21],
  ['Ibirité', 'Contagem', 19],
  ['Ibirité', 'Uberlândia', 525],
  ['Ibirité', 'Juiz de Fora', 267],
  ['Ibirité', 'Ribeirão das Neves', 39],
  ['Ibirité', 'Betim', 22],
  ['Ibirité', 'Montes Claros', 430],
  ['Ibirité', 'Uberaba', 464],
  ['Ibirité', 'Governador Valadares', 336],
  ['Ibirité', 'Santa Luzia', 43],
  ['Ibirité', 'Ipatinga', 236],
  ['Ibirité', 'Sete Lagoas', 77],
  ['Ibirité', 'Divinópolis', 140],
  ['Ibirité', 'Poços de Caldas', 451],
];

export { CITIES, CITY_CONNECTIONS }